baseURL = "https://yoon92kr.github.io/pzparkgolf/"
languageCode = "ko-kr"
title = "PZ 파크골프"
theme = ""
relativeURLs = false
canonifyURLs = true

[params]
  navbarLogo = "images/logo.png"
  custom_css = ["css/custom.css"]
  
  [[menu.main]]
    name = "회사 소개"
    url = "#about"
  [[menu.main]]
    name = "제품 소개"
    url = "#products"
  [[menu.main]]
    name = "설치 문의"
    url = "#contact"
